import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { signOut, useSession } from "next-auth/react";

import { trpc } from "@/utils/trpc";
import { getServerAuthSession } from "@/server/common/get-server-auth-session";
import Layout from "@/components/layout/Layout";
import NavLayout from "@/components/layout/navLayout";


const Dashboard: NextPage = () => {
  const session = useSession();
  const secret = trpc.protected.getSecretMessage.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavLayout />

      <Layout>


      <div className="dark:bg-gray-800 grid justify-items-center min-h-screen">
        {/* < TabsEngine /> */}
        <div> meow </div>
      </div>


      </Layout>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession({
    req: context.req,
    res: context.res,
  });

  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return { props: {} };
};

export default Dashboard;
