import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { trpc } from "@/utils/trpc";
import NavLayout from "@/components/layout/navLayout";

const LoginSuccess: NextPage = () => {
  const { data: session } = useSession();
  const { data, isLoading } = trpc.userAPIs.readCurrentUser.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavLayout />
      {session && (
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-5xl font-extrabold tracking-tight text-black dark:text-white sm:text-[5rem]">
              Hello{" "}
              <span className="text-[hsl(280,100%,70%)]">
                {isLoading || (
                    <span className="text-[hsl(280,100%,70%)]">
                      {data && data?.username}
                    </span>
                  ) || <span className="text-red-600">Meow! No Name</span>}
              </span>
            </h1>
          </div>
          {!data?.address && (
            <div className="flex flex-col items-center">
              <span className="text-red-700">
                {" "}
                Your account needs an address{" "}
              </span>
              <Link
                href={"/account"}
                className="text-center hover:border-hsl(0,0%,6%) hover:text-hsl(0,0%,6%) mt-6 h-10 rounded border border-gray-500 bg-transparent px-4 pt-2 pb-8 font-semibold text-gray-800 hover:bg-[hsl(154,47%,66%)] dark:text-gray-100 dark:hover:text-gray-800"
              >
                Add address
              </Link>
            </div>
          )}

          {!data?.role && (
            <div className="flex flex-col mt-6">
              <span className="text-red-700">
                {" "}
                Your account needs a role{" "}
              </span>
              <Link
                href={"/account"}
                className="text-center hover:border-hsl(0,0%,6%) hover:text-hsl(0,0%,6%) mt-6 h-10 rounded border border-gray-500 bg-transparent px-4 pt-2 pb-8 font-semibold text-gray-800 hover:bg-[hsl(154,47%,66%)] dark:text-gray-100 dark:hover:text-gray-800"
              >
                Add role
              </Link>
            </div>
          )}
        </main>
      )}
      {!session && (
        <main className="justify-top flex min-h-screen flex-col items-center md:justify-center lg:justify-center">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="border-gray-900 text-center text-5xl font-extrabold tracking-tight text-gray-800 dark:text-white sm:text-[5rem]">
              House <span className="text-[hsl(280,100%,70%)]">Call</span>
            </h1>
            <div className="flex flex-row gap-2">
              <Link href={"/signin"} className="rounded border py-1 px-4">
                Sign in
              </Link>
              <Link href={"/register"} className="rounded border py-1 px-4">
                Register
              </Link>
            </div>
          </div>
        </main>
      )}
    </>
  );
};

export default LoginSuccess;
